### PR TITLE
fix rootUri prefix ( win OS platform dependencies. )

### PR DESCRIPTION
**Pull request by stacew**
In my Windows environment, it works only if I modify this part.

please check.

[win10 OS env issue](https://github.com/icapps/flutter-icapps-license/issues/36)

### CODE REVIEW

**Review by NicolaVerbeeck — CHANGES_REQUESTED** [review]
This fix now targets win10 OS only, other platforms are no longer working.

Please add a check for the windows platform

**Comment by stacew** [comment]
> 

hello

Committed by adding platform dependencies.

thank you

**Review by NicolaVerbeeck — APPROVED** [review]

**Comment by NicolaVerbeeck** [comment]
LGTM

**Review by vanlooverenkoen — APPROVED** [review]

**Comment by stacew** [comment]
@NicolaVerbeeck 
i'm not [authorized](https://docs.github.com/articles/about-protected-branches/) to merge this pull request.

Should I ask for open source permission?

**Comment by NicolaVerbeeck** [comment]
@vanlooverenkoen Merge please

**Comment by stacew** [comment]
I thought you were waiting for me to merge.

It's okay for me to merge later : )

**Comment by vanlooverenkoen** [comment]
Released in 1.0.4

**Pull request merged**
